### ISSUE TITLE
What will be the initial steps to get some idea about Medical Data Visualization and whats the proposal

### ISSUE THREAD

**Issue by shradhabasnet1** [sigdelsanjog/medical-data-insight#40]

**Comment by sigdelsanjog** [comment]
FEATURE #42 PROJECT MANAGEMENT incorporates a User Story #27 PROJECT WEBSITE. Completion of this feature will provide all necessary information about **MEDICAL DATA INSIGHT**. This will then also answer your queries about where to begin and how to contribute.
Closing this issue as of now.
